### Basic data types

#### Numbers

Integers and floats work as you would expect from other languages:

In [2]:
x = 3
print(type(x)) # Prints "<class 'int'>"
print(x)

<class 'int'>
3

In [3]:
print(x + 1)   # Addition
print(x - 1)   # Subtraction
print(x * 2)   # Multiplication
print(x ** 2)  # Exponentiation

4
2
6
9

In [4]:
x += 1
print(x)  # Prints "4"
x *= 2
print(x)  # Prints "8"

4
8

In [1]:
y = 2.5
print(type(y)) 
print(y, y + 1, y * 2, y ** 2)

<class 'float'>
2.5 3.5 5.0 6.25

#### Booleans

Python implements all of the usual operators for Boolean logic, but uses English words (`and`, `or`) rather than symbols (`&&`, `||`, etc.):

In [2]:
t = True
f = False
print(type(t)) # Prints "<class 'bool'>"
print(t and f) # Logical AND; prints "False"
print(t or f)  # Logical OR; prints "True"
print(not t)   # Logical NOT; prints "False"
print(t != f)  # Logical XOR; prints "True"

<class 'bool'>
False
True
False
True

#### Strings

Python has great support for strings:

In [3]:
hello = 'hello'    # String literals can use single quotes
world = "world"    # or double quotes; it does not matter.
print(hello)       # Prints "hello"
print(len(hello))  # String length; prints "5"
hw = hello + ' ' + world  # String concatenation
print(hw)  # prints "hello world"

hello
5
hello world

#### Loops

You can loop over the elements of a list like this:

In [ ]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)
# Prints "cat", "dog", "monkey", each on its own line.

cat
dog
monkey

- To use ```while``` loop.

In [4]:
i = 0
while i <5:
    print( i, "th turn")
    i = i+1

0 th turn
1 th turn
2 th turn
3 th turn
4 th turn

- To break for loop implementing ```if``` condition

In [1]:
for i in range(10):
    print(i)
    if i ==3:
        break

0
1
2
3

- To test the if conditions:

In [ ]:
import random as random

for i in range(10):
    r = random.uniform(1,10)
    if r<2 and r>0:
        print("It is samaller then 2 and greater then 1","|", r)
    elif r<4 and r>2:
        print("It is samaller then 4 and greater then 2","|", r)
    elif r<6 and r>4:
        print("It is samaller then 6 and greater then 4","|", r)
    elif r<8 and r>6:
        print("It is samaller then 8 and greater then 6","|", r)
    elif r<10 and r>8:
        print("It is samaller then 10 and greater then 8","|", r)

It is samaller then 4 and greater then 2 | 2.410517743617814
It is samaller then 2 and greater then 1 | 1.538375064588924
It is samaller then 8 and greater then 6 | 7.285759129288541
It is samaller then 4 and greater then 2 | 3.394697773325497
It is samaller then 4 and greater then 2 | 2.914781193163869
It is samaller then 8 and greater then 6 | 6.075534618099542
It is samaller then 4 and greater then 2 | 3.2669891450026602
It is samaller then 6 and greater then 4 | 4.071504548968656
It is samaller then 8 and greater then 6 | 7.3289229412263515
It is samaller then 6 and greater then 4 | 5.816515315392462

# Fundamental Data Structure :

The fundamental data structure in python includes

- **Primitive type** ( ***Integer, Float, String***, and ***Boolean***) and
- **Non-Primitive type** ( ***Array, List, Tuples, Dictionary, Set***, and ***File***)

In this tutorial, we are going to discudd about List, Tuples, Set and Dictionary.



### List

List is built in data structure in python. It is
- Mutable i.e., we can change or edite the size of the list by appending, inserting and deleting the elements.
- List can hold heterogeneous objects (e.g., integer, string, boolean)

Lets try to understand the List:

- To initiate a blank List.

In [6]:
l = []

- To find the type of the object.

In [7]:
type(l)

list

- To create a list from scratch.

In [8]:
L = [1,2,3,4,5,6,342,34]

In [9]:
L

[1, 2, 3, 4, 5, 6, 342, 34]

- Indexing of list.

In [11]:
L[0],L[1],L[5]

(1, 2, 6)

- Revers indexing is also possible.

In [10]:
L[-1],L[-2],L[-3]

(34, 342, 6)

- To find the length of list.

In [12]:
len(L)

8

- To add the element from last.

In [13]:
L.append(12)
L

[1, 2, 3, 4, 5, 6, 342, 34, 12]

- To find the sum of the elements (if they are of same types like int. double etc)

In [14]:
sum(L)

409

- To find maximum and minimum of the list

In [15]:
max(L), min(L)

(342, 1)

- To create a list of heterogeneous element types.

In [16]:
L = [1,2.0,3,4,5,"Apple",True, False]

- To find the type of elements of a list.

In [17]:
type(L[1]),type(L[5])

(float, str)

- To create a list of list.

In [18]:
L = [[1,2,3],[3,4,5],[5,7,9]]

- To find list inside a list.

In [19]:
L[0]

[1, 2, 3]

In [20]:
L[0][1]

2

- To add two list. It is not as ususal addition. The elements are accumulated.

In [21]:
L1 = [1,2,3] ; L2 = [2,4,6]
L1+L2, set(L1+L2)

([1, 2, 3, 2, 4, 6], {1, 2, 3, 4, 6})

- To add element from end of the list

In [22]:
L = [1,4,2,3,5,6,7]
L.append(100)
L

[1, 4, 2, 3, 5, 6, 7, 100]

- To insert element (100) at specific index (1)

In [23]:
L = [1,4,2,3,5,6,7]
L.insert(1,100)
L

[1, 100, 4, 2, 3, 5, 6, 7]

- To remove specific element form list. It will remove the first occurance.

In [24]:
L = [1,4,2,3,5,6,7,4]
L.remove(4)
L

[1, 2, 3, 5, 6, 7, 4]

- To remove the element from specific index

In [25]:
L = [1,4,2,3,5,6,7]
L.pop(-1)
L

[1, 4, 2, 3, 5, 6]

- To sort the list

In [26]:
L = [1,10,2,30,5,60,7]
L.sort()
L

[1, 2, 5, 7, 10, 30, 60]

- To reverse the list

In [27]:
L = [1,4,2,3,5,6,7]
L.reverse()
L

[7, 6, 5, 3, 2, 4, 1]

- List comprehension

In [28]:
L = [x for x in range(100)]
print(L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]

In [29]:
L = [x for x in range(100) if x%2==0]
print(L)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]

In [30]:
import random as rn
rn.randint(0,100)

97

In [31]:
import random as rn
R = [rn.randint(0,100) for k in range(200)]
print(R)

[13, 52, 66, 91, 67, 31, 67, 72, 92, 33, 20, 34, 95, 44, 34, 38, 66, 32, 71, 56, 5, 91, 41, 43, 11, 34, 94, 30, 38, 61, 32, 81, 4, 68, 81, 63, 8, 59, 25, 84, 33, 34, 39, 46, 74, 7, 14, 71, 41, 49, 5, 94, 79, 43, 73, 27, 35, 32, 9, 64, 53, 66, 76, 85, 45, 67, 61, 12, 30, 31, 28, 28, 25, 16, 1, 37, 15, 9, 47, 56, 13, 38, 48, 85, 15, 16, 55, 64, 23, 50, 45, 89, 81, 93, 14, 33, 85, 6, 71, 40, 63, 11, 28, 8, 91, 88, 81, 11, 85, 32, 53, 79, 0, 50, 41, 76, 32, 69, 34, 56, 2, 65, 83, 62, 72, 1, 32, 54, 26, 72, 35, 61, 87, 87, 77, 28, 94, 12, 94, 51, 20, 13, 18, 21, 4, 91, 94, 20, 88, 16, 81, 51, 79, 55, 4, 44, 13, 64, 13, 12, 40, 93, 24, 66, 90, 50, 90, 43, 70, 59, 42, 11, 85, 97, 2, 52, 84, 59, 82, 55, 80, 33, 26, 53, 17, 76, 61, 20, 69, 87, 64, 94, 50, 87, 98, 7, 86, 76, 64, 54]

In [32]:
import collections
#High Performance Counting
C = collections.Counter(R)
print(C)

Counter({32: 6, 94: 6, 13: 5, 34: 5, 81: 5, 64: 5, 85: 5, 66: 4, 91: 4, 33: 4, 20: 4, 11: 4, 61: 4, 76: 4, 28: 4, 50: 4, 87: 4, 67: 3, 72: 3, 38: 3, 71: 3, 56: 3, 41: 3, 43: 3, 4: 3, 59: 3, 79: 3, 53: 3, 12: 3, 16: 3, 55: 3, 52: 2, 31: 2, 44: 2, 5: 2, 30: 2, 63: 2, 8: 2, 25: 2, 84: 2, 7: 2, 14: 2, 35: 2, 9: 2, 45: 2, 1: 2, 15: 2, 93: 2, 40: 2, 88: 2, 69: 2, 2: 2, 54: 2, 26: 2, 51: 2, 90: 2, 92: 1, 95: 1, 68: 1, 39: 1, 46: 1, 74: 1, 49: 1, 73: 1, 27: 1, 37: 1, 47: 1, 48: 1, 23: 1, 89: 1, 6: 1, 0: 1, 65: 1, 83: 1, 62: 1, 77: 1, 18: 1, 21: 1, 24: 1, 70: 1, 42: 1, 97: 1, 82: 1, 80: 1, 17: 1, 98: 1, 86: 1})

In [33]:
R = [rn.choice(['A','T','G','C']) for i in range(200)]
print(R)

['G', 'C', 'G', 'G', 'C', 'G', 'C', 'C', 'C', 'T', 'G', 'C', 'T', 'T', 'G', 'A', 'A', 'C', 'A', 'T', 'G', 'T', 'A', 'G', 'T', 'A', 'C', 'A', 'C', 'G', 'G', 'T', 'G', 'C', 'G', 'T', 'A', 'G', 'C', 'C', 'T', 'T', 'C', 'C', 'A', 'C', 'G', 'A', 'G', 'T', 'G', 'G', 'G', 'A', 'A', 'C', 'C', 'G', 'A', 'C', 'A', 'C', 'T', 'C', 'C', 'T', 'T', 'C', 'G', 'A', 'T', 'G', 'C', 'C', 'T', 'A', 'A', 'T', 'G', 'G', 'A', 'A', 'C', 'T', 'A', 'G', 'A', 'G', 'G', 'C', 'C', 'G', 'C', 'G', 'T', 'A', 'G', 'G', 'C', 'G', 'A', 'T', 'G', 'G', 'G', 'C', 'T', 'T', 'C', 'C', 'C', 'A', 'T', 'T', 'T', 'A', 'T', 'G', 'T', 'G', 'G', 'C', 'C', 'G', 'T', 'A', 'C', 'C', 'G', 'A', 'A', 'A', 'T', 'C', 'G', 'A', 'T', 'T', 'A', 'A', 'C', 'G', 'G', 'T', 'T', 'T', 'C', 'A', 'C', 'A', 'C', 'C', 'T', 'G', 'A', 'G', 'C', 'T', 'C', 'T', 'T', 'C', 'G', 'T', 'C', 'A', 'T', 'C', 'G', 'A', 'T', 'A', 'T', 'T', 'C', 'G', 'T', 'A', 'C', 'G', 'T', 'A', 'G', 'T', 'A', 'G', 'T', 'G', 'A', 'G', 'G', 'T', 'T', 'G', 'A', 'C', 'T', 'A', 'A', 'G']

In [34]:
DNA = ''.join(R)
DNA

'GCGGCGCCCTGCTTGAACATGTAGTACACGGTGCGTAGCCTTCCACGAGTGGGAACCGACACTCCTTCGATGCCTAATGGAACTAGAGGCCGCGTAGGCGATGGGCTTCCCATTTATGTGGCCGTACCGAAATCGATTAACGGTTTCACACCTGAGCTCTTCGTCATCGATATTCGTACGTAGTAGTGAGGTTGACTAAG'

### Tuples

Tuples are non-mutable, which means we can ot add or remove elements once tuple is defind.

- To define a tuples from scratch

In [35]:
t = (2,3,4,5)

- Find type

In [36]:
type(t)

tuple

- Indexing

In [37]:
t[1]

3

In [38]:
L = [(1,2),(2,3),(3,4)]

In [39]:
L[0][0]

1

- Create a list of tuples

In [40]:
L = [(1,2),("a","b"),(True, False)]
L

[(1, 2), ('a', 'b'), (True, False)]

### Dictionary

Dictionary organizes the data with key-value pair. Dictionary can be nested with other data types.

- To initiate a dictionary

In [41]:
D = dict()
DD = {}

- Create a dictionary from scratch

In [42]:
D = {"fruit":'apple',
    "vegetable" : 'carrot',
    "rice": 2.0,
    'milk': 10,}

- What are keys?

In [43]:
D.keys()

dict_keys(['fruit', 'vegetable', 'rice', 'milk'])

- What are values?

In [44]:
D.values()

dict_values(['apple', 'carrot', 2.0, 10])

- Indexing

In [45]:
D['fruit'], D["rice"]

('apple', 2.0)

- Iteration over key and values

In [46]:
for key,value in D.items():
    print(key,value)

fruit apple
vegetable carrot
rice 2.0
milk 10

- To update a dictionary

In [47]:
D.update({"salt": 2.0})
D

{'fruit': 'apple', 'vegetable': 'carrot', 'rice': 2.0, 'milk': 10, 'salt': 2.0}

- To create a list form a Dictionary. Only keys are collected.

In [48]:
list(D)

['fruit', 'vegetable', 'rice', 'milk', 'salt']

- To create a list of keys only

In [49]:
list(D.keys())

['fruit', 'vegetable', 'rice', 'milk', 'salt']

- To create a list of values

In [50]:
list(D.values())

['apple', 'carrot', 2.0, 10, 2.0]

- To create Dictionary of with list, tuples and dictionary

In [51]:
DD = {"names":("John","Harry", "Brat"),\
      "roll no": [1,2,3],\
      "plan":{"first":[12,34,56],"second":[1,3,5]}}

DD

{'names': ('John', 'Harry', 'Brat'),
 'roll no': [1, 2, 3],
 'plan': {'first': [12, 34, 56], 'second': [1, 3, 5]}}

In [52]:
# Empty set
empty_set = set()
print(type(empty_set))  # <class 'set'>

# Set with initial values
fruits = {'apple', 'banana', 'orange'}
print(fruits)  # {'banana', 'orange', 'apple'}

# Creating set from a list
numbers = set([1, 2, 3, 2, 1])  # Duplicates removed
print(numbers)  # {1, 2, 3}

<class 'set'>
{'banana', 'orange', 'apple'}
{1, 2, 3}

In [53]:
colors = {'red', 'green', 'blue'}

# Unordered (no index access)

# No duplicates
unique_nums = {1, 2, 2, 3, 3, 3}
print(unique_nums)  # {1, 2, 3}

# Mutable (can add/remove items)
colors.add('yellow')
print(colors)  # {'red', 'green', 'blue', 'yellow'}

# Length of set
print(len(colors))  # 4

{1, 2, 3}
{'blue', 'red', 'yellow', 'green'}
4

In [54]:
s = {1, 2, 3}

# Adding elements
s.add(4)
print(s)  # {1, 2, 3, 4}

# Removing elements
s.remove(2)  # Raises KeyError if element doesn't exist
s.discard(5)  # No error if element doesn't exist
print(s)  # {1, 3, 4}

# Pop random element
popped = s.pop()
print(f"Popped: {popped}, Remaining: {s}")

# Clear all elements
s.clear()
print(s)  # set()

# Copy set
new_set = {1, 2, 3}.copy()

{1, 2, 3, 4}
{1, 3, 4}
Popped: 1, Remaining: {3, 4}
set()

In [55]:
fs = frozenset([1, 2, 3, 3])
print(fs)  # frozenset({1, 2, 3})

frozenset({1, 2, 3})

In [56]:
import numpy as np

In [57]:
nums1 = [1,2,3,4,5]
nums2 = np.array(nums1)

In [58]:
nums1, nums2

([1, 2, 3, 4, 5], array([1, 2, 3, 4, 5]))

In [59]:
type(nums1), type(nums2)

(list, numpy.ndarray)

In [61]:
x1 = np.array([3,4,5], dtype='int8')

In [62]:
x1.dtype

dtype('int8')

In [63]:
x1.shape

(3,)

In [ ]:
x2 = np.arange(20, 50, 2)
x2

In [64]:
np.linspace(10, 20, 10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [65]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [66]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [67]:
x4 = np.random.random((3,5))
x4

array([[0.65441234, 0.50063525, 0.39126913, 0.07692507, 0.40009306],
       [0.54519803, 0.57664218, 0.41263116, 0.59631601, 0.56947437],
       [0.09355203, 0.18608508, 0.36159138, 0.04191388, 0.21851232]])

In [68]:
x4.dtype

dtype('float64')

In [69]:
x4.shape

(3, 5)

In [70]:
x4.reshape(5,3)

array([[0.65441234, 0.50063525, 0.39126913],
       [0.07692507, 0.40009306, 0.54519803],
       [0.57664218, 0.41263116, 0.59631601],
       [0.56947437, 0.09355203, 0.18608508],
       [0.36159138, 0.04191388, 0.21851232]])

In [71]:
x4.T

array([[0.65441234, 0.54519803, 0.09355203],
       [0.50063525, 0.57664218, 0.18608508],
       [0.39126913, 0.41263116, 0.36159138],
       [0.07692507, 0.59631601, 0.04191388],
       [0.40009306, 0.56947437, 0.21851232]])

In [72]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [73]:
A = np.arange(9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [75]:
# first row
A[0]

array([0, 1, 2])

In [74]:
# second row, second col
A[1,1]

np.int64(4)

### ```time```

In [76]:
import time

t1 = time.time()
for i in range(1000001):
    if i==1000000:
        print("done!")

t2 = time.time()
t2-t1

done!

0.2118544578552246

### ```tqdm```

In [77]:
import time
from tqdm import tqdm

mylist = [i for i in range(100)]

for i in tqdm(mylist):
    time.sleep(0.5)

100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:50<00:00,  1.99it/s]

### ```glob```

In [78]:
import glob
glob.glob('*.ipynb')

['01_EDA_Demo.ipynb',
 '01_stats_demo_explanation .ipynb',
 '01_stats_demo_explanation.ipynb',
 '02_EDA_Worksheet.ipynb',
 '02_student_tasks (1).ipynb',
 '04_StatAnalysis_Demo.ipynb',
 '05_StatAnalysis_Worksheet.ipynb',
 '1_DataStructure.ipynb',
 'Basic Vector Operations and iris data.ipynb',
 'Basics of Python.ipynb',
 'bigram_trigram.ipynb',
 'DataStructures_Worksheet.ipynb',
 'Data_Visualization.ipynb',
 'Data_Visualization_Worksheet.ipynb',
 'distributions_lecture .ipynb',
 'distributions_tasks.ipynb',
 'EDA_Assignment_NYC_Airbnb (1).ipynb',
 'fifa_challenge.ipynb',
 'hypothesis_testing_courtroom (2).ipynb',
 'hyp_test_worksheet (2).ipynb',
 'Mini Project.ipynb',
 'Probability Concept with Real  world example.ipynb',
 'Probability_distribution_and_basic_ML.ipynb',
 'stat_tools_guide.ipynb',
 'stat_worksheet_v3.ipynb',
 'syntax_helpsheet.ipynb',
 'Titanic_Dataset.ipynb']

### ```os```

In [79]:
import os
path = "plot"
os.path.isdir(path)

False

In [80]:
path = "1. DataStructure.ipynb"
os.path.isfile(path)

False

In [82]:
os.listdir()

['.ipynb_checkpoints',
 '01_EDA_Demo.ipynb',
 '01_stats_demo_explanation .ipynb',
 '01_stats_demo_explanation.ipynb',
 '02_EDA_Worksheet.ipynb',
 '02_student_tasks (1).ipynb',
 '04_StatAnalysis_Demo.ipynb',
 '05_StatAnalysis_Worksheet.ipynb',
 '1_DataStructure.ipynb',
 'AB_NYC_2019.csv',
 'Basic Vector Operations and iris data.ipynb',
 'Basics of Python.ipynb',
 'bigram_trigram.ipynb',
 'DataStructures_Worksheet.ipynb',
 'Data_Visualization.ipynb',
 'Data_Visualization_Worksheet.ipynb',
 'distributions_lecture .ipynb',
 'distributions_tasks.ipynb',
 'EDA_Assignment_NYC_Airbnb (1).ipynb',
 'fifa_challenge.ipynb',
 'hypothesis_testing_courtroom (2).ipynb',
 'hyp_test_worksheet (2).ipynb',
 'input.txt',
 'LOM HAW hamburg.pdf',
 'M2 L2 Overview AI pipeline CI CD.pptx',
 'Mini Project.ipynb',
 'NAVTCC_AI_ML_Course.pdf',
 'NAVTCC_AI_ML_Course1.pdf',
 'NETSOL_Al_ML Course.pdf',
 'Probability Concept with Real  world example.ipynb',
 'Probability_distribution_and_basic_ML.ipynb',
 'readme',
 'SMSSpamCollection',
 'stat_tools_guide.ipynb',
 'stat_worksheet_v3.ipynb',
 'syntax_helpsheet.ipynb',
 'Titanic-Dataset.csv',
 'Titanic_Dataset.ipynb',
 '_Vision Board.png']


### 1. Loading and Exploring the Iris Dataset

In [83]:
import pandas as pd
from sklearn.datasets import load_iris

# Load the iris dataset
iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['species'] = iris.target_names[iris.target]

# Display basic information
print("First 5 rows:")
display(iris_df.head())

print("\nLast 5 rows:")
display(iris_df.tail())

print("\nDataset info:")
iris_df.info()

print("\nBasic statistics:")
display(iris_df.describe())

First 5 rows:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

Last 5 rows:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

Dataset info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   species            150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

Basic statistics:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

### 2. Selecting Data

In [84]:
# Select a single column
sepal_length = iris_df['sepal length (cm)']
print("Sepal length column:")
display(sepal_length.head())

# Select multiple columns
sepal_data = iris_df[['sepal length (cm)', 'sepal width (cm)']]
print("\nSepal measurements:")
display(sepal_data.head())

# Select rows by position
first_10 = iris_df.iloc[:10]
print("\nFirst 10 rows:")
display(first_10)

# Select rows by condition
setosa = iris_df[iris_df['species'] == 'setosa']
print("\nSetosa samples:")
display(setosa.head())

Sepal length column:

0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
Name: sepal length (cm), dtype: float64

Sepal measurements:

   sepal length (cm)  sepal width (cm)
0                5.1               3.5
1                4.9               3.0
2                4.7               3.2
3                4.6               3.1
4                5.0               3.6

First 10 rows:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
5,5.4,3.9,1.7,0.4,setosa
6,4.6,3.4,1.4,0.3,setosa
7,5.0,3.4,1.5,0.2,setosa
8,4.4,2.9,1.4,0.2,setosa
9,4.9,3.1,1.5,0.1,setosa

Setosa samples:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

### 3. Data Manipulation

In [ ]:
# Add a new calculated column
iris_df['sepal_ratio'] = iris_df['sepal length (cm)'] / iris_df['sepal width (cm)']
print("DataFrame with new sepal ratio column:")
display(iris_df.head())

# Group by species
grouped = iris_df.groupby('species')
print("\nMean values by species:")
display(grouped.mean())

# Sort by petal length
sorted_df = iris_df.sort_values('petal length (cm)', ascending=False)
print("\nTop 5 flowers by petal length:")
display(sorted_df.head())

DataFrame with new sepal ratio column:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species,sepal_ratio
0,5.1,3.5,1.4,0.2,setosa,1.457143
1,4.9,3.0,1.4,0.2,setosa,1.633333
2,4.7,3.2,1.3,0.2,setosa,1.468750
3,4.6,3.1,1.5,0.2,setosa,1.483871
4,5.0,3.6,1.4,0.2,setosa,1.388889

Mean values by species:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),sepal_ratio
species,,,,,
setosa,5.006,3.428,1.462,0.246,1.470188
versicolor,5.936,2.770,4.260,1.326,2.160402
virginica,6.588,2.974,5.552,2.026,2.230453

Top 5 flowers by petal length:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species,sepal_ratio
118,7.7,2.6,6.9,2.3,virginica,2.961538
122,7.7,2.8,6.7,2.0,virginica,2.750000
117,7.7,3.8,6.7,2.2,virginica,2.026316
105,7.6,3.0,6.6,2.1,virginica,2.533333
131,7.9,3.8,6.4,2.0,virginica,2.078947